/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Wed Nov 01 11:54:25 2006
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-v" "-T"
 * "compile:exe" "saccv20a.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_saccv20a_public_data[] = {'3', '0', '8', '1', '9',
                                                    'D', '3', '0', '0', 'D',
                                                    '0', '6', '0', '9', '2',
                                                    'A', '8', '6', '4', '8',
                                                    '8', '6', 'F', '7', '0',
                                                    'D', '0', '1', '0', '1',
                                                    '0', '1', '0', '5', '0',
                                                    '0', '0', '3', '8', '1',
                                                    '8', 'B', '0', '0', '3',
                                                    '0', '8', '1', '8', '7',
                                                    '0', '2', '8', '1', '8',
                                                    '1', '0', '0', 'C', '4',
                                                    '9', 'C', 'A', 'C', '3',
                                                    '4', 'E', 'D', '1', '3',
                                                    'A', '5', '2', '0', '6',
                                                    '5', '8', 'F', '6', 'F',
                                                    '8', 'E', '0', '1', '3',
                                                    '8', 'C', '4', '3', '1',
                                                    '5', 'B', '4', '3', '1',
                                                    '5', '2', '7', '7', 'E',
                                                    'D', '3', 'F', '7', 'D',
                                                    'A', 'E', '5', '3', '0',
                                                    '9', '9', 'D', 'B', '0',
                                                    '8', 'E', 'E', '5', '8',
                                                    '9', 'F', '8', '0', '4',
                                                    'D', '4', 'B', '9', '8',
                                                    '1', '3', '2', '6', 'A',
                                                    '5', '2', 'C', 'C', 'E',
                                                    '4', '3', '8', '2', 'E',
                                                    '9', 'F', '2', 'B', '4',
                                                    'D', '0', '8', '5', 'E',
                                                    'B', '9', '5', '0', 'C',
                                                    '7', 'A', 'B', '1', '2',
                                                    'E', 'D', 'E', '2', 'D',
                                                    '4', '1', '2', '9', '7',
                                                    '8', '2', '0', 'E', '6',
                                                    '3', '7', '7', 'A', '5',
                                                    'F', 'E', 'B', '5', '6',
                                                    '8', '9', 'D', '4', 'E',
                                                    '6', '0', '3', '2', 'F',
                                                    '6', '0', 'C', '4', '3',
                                                    '0', '7', '4', 'A', '0',
                                                    '4', 'C', '2', '6', 'A',
                                                    'B', '7', '2', 'F', '5',
                                                    '4', 'B', '5', '1', 'B',
                                                    'B', '4', '6', '0', '5',
                                                    '7', '8', '7', '8', '5',
                                                    'B', '1', '9', '9', '0',
                                                    '1', '4', '3', '1', '4',
                                                    'A', '6', '5', 'F', '0',
                                                    '9', '0', 'B', '6', '1',
                                                    'F', 'C', '2', '0', '1',
                                                    '6', '9', '4', '5', '3',
                                                    'B', '5', '8', 'F', 'C',
                                                    '8', 'B', 'A', '4', '3',
                                                    'E', '6', '7', '7', '6',
                                                    'E', 'B', '7', 'E', 'C',
                                                    'D', '3', '1', '7', '8',
                                                    'B', '5', '6', 'A', 'B',
                                                    '0', 'F', 'A', '0', '6',
                                                    'D', 'D', '6', '4', '9',
                                                    '6', '7', 'C', 'B', '1',
                                                    '4', '9', 'E', '5', '0',
                                                    '2', '0', '1', '1', '1'
                                                    , '\0'};

const char *__MCC_saccv20a_name_data = "saccv20a";

const char *__MCC_saccv20a_root_data = "";

const unsigned char __MCC_saccv20a_session_data[] = {'A', '7', 'F', 'C', '7',
                                                     '3', '3', 'A', 'A', 'D',
                                                     'A', '6', 'C', '4', '2',
                                                     '8', 'A', '4', 'C', 'F',
                                                     '3', '3', 'A', 'E', '0',
                                                     'C', '8', 'C', '5', 'E',
                                                     'E', 'E', '0', '7', 'E',
                                                     '4', '7', '3', 'E', '6',
                                                     'A', 'B', '3', '3', '6',
                                                     'D', 'B', 'D', '9', '7',
                                                     '8', '9', 'A', '7', 'C',
                                                     '4', 'A', '0', '8', 'A',
                                                     'D', '4', '0', '7', 'C',
                                                     '3', 'C', 'B', '8', '0',
                                                     '9', '5', 'C', 'A', 'B',
                                                     '1', '7', '0', '3', '8',
                                                     'C', 'C', 'E', '4', 'A',
                                                     'F', 'B', 'A', '8', '1',
                                                     '5', 'F', '5', 'D', 'F',
                                                     'D', 'D', '9', '2', '9',
                                                     '3', 'F', '8', 'E', 'D',
                                                     '9', '5', 'B', '1', '9',
                                                     '9', '8', '7', '9', '3',
                                                     '8', '8', 'C', '4', '6',
                                                     'C', 'C', '1', 'A', 'F',
                                                     '7', 'E', '1', '4', '6',
                                                     '8', '6', 'B', 'D', '0',
                                                     'E', '4', '9', 'B', '8',
                                                     '1', 'F', 'A', '1', '6',
                                                     '3', 'C', 'C', '8', '7',
                                                     'E', '4', '6', '1', 'D',
                                                     '1', '8', 'A', '8', 'E',
                                                     '6', '4', 'C', '9', 'E',
                                                     '6', '7', '8', '4', '0',
                                                     'D', 'F', '6', '7', '9',
                                                     '0', '4', '4', 'F', 'B',
                                                     '3', '1', 'E', '3', 'A',
                                                     '1', 'F', 'D', 'B', '1',
                                                     'C', '6', '2', '7', '9',
                                                     'E', 'B', 'B', '0', '5',
                                                     '7', '2', '5', '1', '4',
                                                     '6', 'E', 'F', 'A', '5',
                                                     'B', '4', '1', 'E', 'F',
                                                     '2', 'A', 'E', 'A', '8',
                                                     'B', '1', 'E', 'F', '8',
                                                     '3', '6', '5', '0', '3',
                                                     '3', '8', '7', '6', '6',
                                                     '9', 'D', '6', 'D', 'F',
                                                     '7', '3', 'B', '1', '1',
                                                     '3', '2', '5', '5', '9',
                                                     'C', 'D', '8', 'F', 'A',
                                                     '6', '\0'};

const char *__MCC_saccv20a_matlabpath_data[] = {"saccv20a/",
                                                "toolbox/compiler/deploy/",
                                                "$TOOLBOXMATLABDIR/general/",
                                                "$TOOLBOXMATLABDIR/ops/",
                                                "$TOOLBOXMATLABDIR/lang/",
                                                "$TOOLBOXMATLABDIR/elmat/",
                                                "$TOOLBOXMATLABDIR/elfun/",
                                                "$TOOLBOXMATLABDIR/specfun/",
                                                "$TOOLBOXMATLABDIR/matfun/",
                                                "$TOOLBOXMATLABDIR/datafun/",
                                                "$TOOLBOXMATLABDIR/polyfun/",
                                                "$TOOLBOXMATLABDIR/funfun/",
                                                "$TOOLBOXMATLABDIR/sparfun/",
                                                "$TOOLBOXMATLABDIR/scribe/",
                                                "$TOOLBOXMATLABDIR/graph2d/",
                                                "$TOOLBOXMATLABDIR/graph3d/",
                                                "$TOOLBOXMATLABDIR/specgraph/",
                                                "$TOOLBOXMATLABDIR/graphics/",
                                                "$TOOLBOXMATLABDIR/uitools/",
                                                "$TOOLBOXMATLABDIR/strfun/",
                                                "$TOOLBOXMATLABDIR/imagesci/",
                                                "$TOOLBOXMATLABDIR/iofun/",
                                                "$TOOLBOXMATLABDIR/audiovideo/",
                                                "$TOOLBOXMATLABDIR/timefun/",
                                                "$TOOLBOXMATLABDIR/datatypes/",
                                                "$TOOLBOXMATLABDIR/verctrl/",
                                                "$TOOLBOXMATLABDIR/codetools/",
                                                "$TOOLBOXMATLABDIR/helptools/",
                                                "$TOOLBOXMATLABDIR/winfun/",
                                                "$TOOLBOXMATLABDIR/demos/",
                                                "toolbox/local/",
                                                "toolbox/compiler/",
                                                "toolbox/map/map/",
                                                "toolbox/map/mapdisp/",
                                                "toolbox/map/mapproj/"};
const int __MCC_saccv20a_matlabpath_data_count = 35;

const char *__MCC_saccv20a_mcr_application_options[] = { "" };
const int __MCC_saccv20a_mcr_application_option_count = 0;
const char *__MCC_saccv20a_mcr_runtime_options[] = { "" };
const int __MCC_saccv20a_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


